CREATE TABLE `ci_gdhk` (
  `uuid` varchar(128) NOT NULL DEFAULT '',
  `ci_code` varchar(14) NOT NULL COMMENT '配置项编码',
  `ci_name` varchar(64) NOT NULL COMMENT '名称',
  `position` varchar(20) NOT NULL COMMENT '位置',
  `mfrs` varchar(64) DEFAULT NULL COMMENT '制造商',
  `model` varchar(64) NOT NULL COMMENT '型号',
  `sn` varchar(64) DEFAULT NULL COMMENT '序列号',
  `ci_desc` varchar(64) DEFAULT NULL COMMENT '配置项描述',
  `team` varchar(16) NOT NULL COMMENT '所属团队',
  `subclass` varchar(16) NOT NULL COMMENT '配置项子类',
  `status` varchar(8) NOT NULL COMMENT '状态',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `ci_physical_server` (
  `uuid` varchar(128) NOT NULL DEFAULT '',
  `ci_code` varchar(14) NOT NULL COMMENT '配置项编码',
  `ci_name` varchar(64) NOT NULL COMMENT '名称',
  `position` varchar(20) NOT NULL COMMENT '位置',
  `asset_no` varchar(16) DEFAULT NULL COMMENT '资产编号',
  `maintenance_unit` varchar(64) DEFAULT NULL,
  `startdate` varchar(16) DEFAULT NULL COMMENT '维保开始时间',
  `enddate` varchar(16) DEFAULT NULL COMMENT '维保结束时间',
  `sn` varchar(64) NOT NULL COMMENT '序列号',
  `model` varchar(64) NOT NULL COMMENT '型号',
  `mfrs` varchar(64) DEFAULT NULL COMMENT '制造商',
  `microcode_version` varchar(64) DEFAULT NULL COMMENT '微码版本',
  `ip` varchar(64) DEFAULT NULL COMMENT 'IP地址',
  `ci_desc` varchar(64) DEFAULT NULL COMMENT '配置项描述',
  `team` varchar(16) NOT NULL COMMENT '所属团队',
  `subclass` varchar(16) NOT NULL COMMENT '配置项子类',
  `status` varchar(8) NOT NULL COMMENT '状态',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `ci_network_device` (
  `uuid` varchar(128) NOT NULL DEFAULT '',
  `ci_code` varchar(14) NOT NULL COMMENT '配置项编码',
  `ci_name` varchar(64) NOT NULL COMMENT '名称',
  `position` varchar(20) NOT NULL COMMENT '位置',
  `asset_no` varchar(16) DEFAULT NULL COMMENT '资产编号',
  `maintenance_unit` varchar(64) DEFAULT NULL,
  `startdate` varchar(16) DEFAULT NULL COMMENT '维保开始时间',
  `enddate` varchar(16) DEFAULT NULL COMMENT '维保结束时间',
  `sn` varchar(64) NOT NULL COMMENT '序列号',
  `model` varchar(64) NOT NULL COMMENT '型号',
  `mfrs` varchar(64) DEFAULT NULL COMMENT '制造商',
  `ios_version` varchar(64) DEFAULT NULL COMMENT 'IOS版本',
  `ip` varchar(64) DEFAULT NULL COMMENT 'IP地址',
  `network_type` varchar(64) DEFAULT NULL COMMENT '网络类别',
  `network_area` varchar(64) DEFAULT NULL COMMENT '网络区域',
  `ci_desc` varchar(64) DEFAULT NULL COMMENT '配置项描述',
  `team` varchar(16) NOT NULL COMMENT '所属团队',
  `subclass` varchar(16) NOT NULL COMMENT '配置项子类',
  `status` varchar(8) NOT NULL COMMENT '状态',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `ci_storage` (
  `uuid` varchar(128) NOT NULL DEFAULT '',
  `ci_code` varchar(14) NOT NULL COMMENT '配置项编码',
  `ci_name` varchar(64) NOT NULL COMMENT '名称',
  `position` varchar(20) NOT NULL COMMENT '位置',
  `asset_no` varchar(16) DEFAULT NULL COMMENT '资产编号',
  `maintenance_unit` varchar(64) DEFAULT NULL,
  `startdate` varchar(16) DEFAULT NULL COMMENT '维保开始时间',
  `enddate` varchar(16) DEFAULT NULL COMMENT '维保结束时间',
  `sn` varchar(64) NOT NULL COMMENT '序列号',
  `model` varchar(64) NOT NULL COMMENT '型号',
  `mfrs` varchar(64) DEFAULT NULL COMMENT '制造商',
  `alcapacity` varchar(8) DEFAULT NULL COMMENT '设备容量',
  `ci_desc` varchar(64) DEFAULT NULL COMMENT '配置项描述',
  `team` varchar(16) NOT NULL COMMENT '所属团队',
  `subclass` varchar(16) NOT NULL COMMENT '配置项子类',
  `status` varchar(8) NOT NULL COMMENT '状态',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `ip_pool` (
  `uuid` varchar(128) NOT NULL COMMENT '唯一标识',
  `ip_address` varchar(64) DEFAULT NULL COMMENT 'ip地址',
  `state` int(4) DEFAULT NULL COMMENT '状态：1未分配，2已分配',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `network_uuid` varchar(128) DEFAULT NULL COMMENT '关联网络',
  PRIMARY KEY (`uuid`),
  KEY `network_uuid` (`network_uuid`),
  CONSTRAINT `ip_pool_ibfk_1` FOREIGN KEY (`network_uuid`) REFERENCES `network` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ip池';
