CREATE TABLE `physical_machine` (
  `uuid` varchar(128) NOT NULL COMMENT '主键UUID唯一标识',
  `name` varchar(128) DEFAULT NULL COMMENT '名称',
  `ip` varchar(64) DEFAULT NULL COMMENT 'IP地址',
  `mac` varchar(64) DEFAULT NULL COMMENT 'Mac地址',
  `state` int(4) DEFAULT NULL COMMENT '状态：0：异常，1：创建中，2：运行，3:  修改中，4：开机中，5：关机中，6：已关机，7：重启中，8：已删除',
  `username` varchar(128) DEFAULT NULL COMMENT '用户名',
  `password` varchar(128) DEFAULT NULL COMMENT '密码',
  `cpu_num` int(11) DEFAULT NULL COMMENT '处理器（核）',
  `mem_size` double(11,0) DEFAULT NULL COMMENT '内存（G）',
  `disk_size` double(11,0) DEFAULT NULL COMMENT '磁盘大小（G）',
  `description` varchar(200) DEFAULT NULL COMMENT '描述',
  `datacenter_uuid` varchar(128) DEFAULT NULL COMMENT '关联到数据中心',
  `zone_uuid` varchar(128) DEFAULT NULL COMMENT '关联到区域',
  `pool_uuid` varchar(128) DEFAULT NULL COMMENT '关联到资源池',
  `cluster_uuid` varchar(128) DEFAULT NULL COMMENT '关联到集群',
  `user_uuid` varchar(128) DEFAULT NULL COMMENT '所属用户',
  `location` varchar(128) DEFAULT NULL COMMENT '位置信息',
  `purpose` varchar(128) DEFAULT NULL COMMENT '用途信息',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`uuid`),
  KEY `datacenter_uuid` (`datacenter_uuid`),
  KEY `zone_uuid` (`zone_uuid`),
  KEY `pool_uuid` (`pool_uuid`),
  KEY `cluster_uuid` (`cluster_uuid`),
  KEY `user_uuid` (`user_uuid`),
  CONSTRAINT `physical_machine_ibfk_1` FOREIGN KEY (`datacenter_uuid`) REFERENCES `datacenter` (`uuid`),
  CONSTRAINT `physical_machine_ibfk_2` FOREIGN KEY (`zone_uuid`) REFERENCES `zone` (`uuid`),
  CONSTRAINT `physical_machine_ibfk_3` FOREIGN KEY (`pool_uuid`) REFERENCES `pool` (`uuid`),
  CONSTRAINT `physical_machine_ibfk_4` FOREIGN KEY (`cluster_uuid`) REFERENCES `cluster` (`uuid`),
  CONSTRAINT `physical_machine_ibfk_5` FOREIGN KEY (`user_uuid`) REFERENCES `sys_user` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='物理机';